language: python
dist: xenial
sudo: required
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      python: "3.7"
      install:
        - pip install -U pip setuptools flake8
      script:
        - flake8

script:
  - tox

# after_success:
#   - |
#     if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then
#       pushd src
#       bash <(curl -s https://codecov.io/bash)
#       popd
#     fi
