language: python
dist: xenial
sudo: required
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      python: "3.7"
      install:
        - pip install -U pip setuptools flake8
      script:
        - flake8

before_install:
  - sudo apt-get -y install gdb

install:
  - pip install -U pip setuptools tox tox-travis

script:
  - tox -- -n4 -v
