matrix:
  include:
    - os: linux
      language: python
      python: 2.7
      cache: pip
      env: TARGET=ci-test
    - os: linux
      language: python
      python: 3.4
      cache: pip
      env: TARGET=ci-test
    - os: linux
      language: python
      python: 3.5
      cache: pip
      env: TARGET=ci-test
    - os: linux
      language: python
      python: 3.6
      cache: pip
      env: TARGET=ci-test
    - os: linux
      language: python
      python: "3.7-dev"
      cache: pip
      env: TARGET=ci-test
    - os: linux
      language: python
      python: 3.6
      env: TARGET=ci-lint
    - os: linux
      language: python
      python: "3.6-dev"
      env: TARGET=ci-coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - os: osx
      language: generic
      env:
        - PYENV_VERSION=2.7.12
        - TARGET=ci-osx-test
    - os: osx
      language: generic
      env: 
        - INSTALL_TYPE=macpython
        - VERSION=3.6
        - VENV=venv
        - TARGET=ci-osx-test
        - TEST_PTVSD_OSXPYVER36=True

before_install: |
  if [ "$TEST_PTVSD_OSXPYVER36" == "True" ]; then
    git clone https://github.com/MacPython/terryfy.git
    source terryfy/travis_tools.sh
    get_python_environment $INSTALL_TYPE $VERSION $VENV
    export TRAVIS_PYTHON_PATH=`which python`
    $TRAVIS_PYTHON_PATH -m pip install --upgrade pip
    $TRAVIS_PYTHON_PATH -m pip install --upgrade pytest
  else
    # Travis comes with an ancient version of pytest preinstalled globally,
    # which breaks automatic dependency checks for setup.py. Force upgrade.
    export TRAVIS_PYTHON_PATH=`which python`
    $TRAVIS_PYTHON_PATH -m pip install --upgrade pip
    $TRAVIS_PYTHON_PATH -m pip install --upgrade pytest
  fi

install:
  - make depends PYTHON=$TRAVIS_PYTHON_PATH

script:
  #- make $TARGET PYTHON=python$TRAVIS_PYTHON_VERSION
  - make $TARGET PYTHON=$TRAVIS_PYTHON_PATH
